### ISSUE TITLE
Not compatible with pointycastle 3.7.0 when compiling to native code

### ISSUE THREAD

**Issue by tomyeh** [Ephenodrom/Dart-Basic-Utils#84]
When compiling our code into an executable (`dart compile exe...`), we ran into this error:

```
/Users/tomyeh/.pub-cache/hosted/pub.dev/basic_utils-5.5.1/lib/src/library/crypto/rc2_engine.dart:4:1: Error: 'RC2Parameters' is imported from both 'package:basic_utils/src/library/crypto/rc2_parameters.dart' and 'package:pointycastle/api.dart'.
import 'package:pointycastle/export.dart';
^^^^^^^^^^^^^
Error: AOT compilation failed
```

FYI, it works fine with `pointycastle 3.6.2`.

**Comment by Ephenodrom** [comment]
Hello I released the pointycastle version 3.7.0 yesterday and i portet some class from this package to pointycastle. I will update basic_utils within the next days.

**Comment by Ephenodrom** [comment]
Version 5.5.2 is now available on pub.dev and makes this package compatible with the latest pointycastle release.
